"""Research orchestration tools combining multiple MCP capabilities."""

from __future__ import annotations

import logging
from typing import Any

from fastmcp import FastMCP

from app.analysis.mermaid_generator import MermaidGenerator
from app.config import get_settings
from app.logging_config import tool_logging
from app.logging_utils import log_event, log_operation
from app.mcp_client import get_client
from app.mcp_types import ToolPayload
from app.tools.network import build_citation_network_impl
from app.tools.search import semantic_search_impl
from app.tools.treatment import check_case_validity_impl
from app.tools.verification import batch_verify_quotes_impl

LEGAL_DISCLAIMER = (
    "\n\n---\n"
    "**DISCLAIMER:** This research was generated by an AI assistant for educational and research purposes only. "
    "It does NOT constitute legal advice. All citations and treatment analysis should be independently verified "
    "before use in any legal proceeding."
)

logger = logging.getLogger(__name__)

research_server: FastMCP[ToolPayload] = FastMCP(
    name="Research Workflow Tools",
    instructions=(
        "Coordinated research tools that assemble citation lookups, treatment analysis, "
        "quote verification, citation-network building, and mermaid rendering for visual summaries."
    ),
)


def _format_key_questions(key_questions: list[str]) -> list[str]:
    """Normalize the key questions list."""
    return [q for q in key_questions if q.strip()]


async def _analyze_citation(
    citation: str,
    scope: str | None,
    mermaid_generator: MermaidGenerator,
    request_id: str | None,
) -> dict[str, Any]:
    """Gather treatment, network, and visualization details for a citation."""
    query_params = {"citation": citation, "scope": scope}
    settings = get_settings()
    client = get_client()

    with log_operation(
        logger,
        tool_name="research_pipeline_case",
        request_id=request_id,
        query_params=query_params,
        event="research_pipeline_case",
    ):
        lookup = await client.lookup_citation(citation, request_id=request_id)

        if "error" in lookup:
            return {"citation": citation, "error": lookup.get("error", "Lookup failed")}

        treatment = await check_case_validity_impl(citation, request_id=request_id)
        network = await build_citation_network_impl(
            citation=citation,
            max_depth=settings.network_max_depth,
            max_nodes=settings.max_citing_cases,
            include_treatments=True,
            request_id=request_id,
        )

        mermaid = None
        if "error" not in network and network.get("nodes"):
            mermaid = mermaid_generator.generate_flowchart(network)

        case_summary = treatment.get("summary") if isinstance(treatment, dict) else None
        log_event(
            logger,
            "Completed research aggregation for citation",
            tool_name="research_pipeline_case",
            request_id=request_id,
            query_params=query_params,
            extra_context={"case_name": lookup.get("caseName"), "has_mermaid": bool(mermaid)},
        )

        return {
            "citation": citation,
            "case_name": lookup.get("caseName"),
            "court": lookup.get("court"),
            "date_filed": lookup.get("dateFiled"),
            "treatment": treatment,
            "network": network,
            "mermaid": mermaid,
            "summary": case_summary,
        }


async def run_research_pipeline_impl(
    citations: list[str],
    key_questions: list[str] | None = None,
    scope: str | None = None,
    quotes: list[dict[str, str]] | None = None,
    request_id: str | None = None,
) -> dict[str, Any]:
    """Execute a coordinated research workflow across citations and questions.

    Args:
        citations: List of citations to analyze.
        key_questions: Optional research questions.
        scope: Optional scope or jurisdiction focus.
        quotes: Optional list of quotes to verify.

    Returns:
        Dictionary containing a markdown summary and machine-readable sections.
    """

    if not citations:
        return {"error": "At least one citation is required"}

    questions = _format_key_questions(key_questions or [])
    mermaid_generator = MermaidGenerator()

    case_results = []
    for citation in citations:
        case_results.append(
            await _analyze_citation(citation, scope, mermaid_generator, request_id)
        )

    quote_results: dict[str, Any] | None = None
    if quotes:
        quote_results = await batch_verify_quotes_impl(quotes, request_id=request_id)

    summary_lines: list[str] = ["# Research Pipeline Summary"]
    if scope:
        summary_lines.append(f"*Scope:* {scope}")

    summary_lines.append("## Key Questions")
    if questions:
        summary_lines.extend([f"- {question}" for question in questions])
    else:
        summary_lines.append("- No key questions provided")

    summary_lines.append("\n## Case Findings")
    for case in case_results:
        if case.get("error"):
            summary_lines.append(f"- **{case['citation']}**: {case['error']}")
            continue

        summary = case.get("summary") or "No treatment summary available"
        citation_label = f"{case.get('citation')} – {case.get('case_name', 'Unknown case')}"
        summary_lines.append(f"- **{citation_label}**: {summary}")

        network_stats = case.get("network", {}).get("statistics")
        if network_stats:
            summary_lines.append(
                f"  - Network: {network_stats.get('total_nodes', 0)} nodes, "
                f"{network_stats.get('total_edges', 0)} edges"
            )
        if case.get("mermaid"):
            summary_lines.append("  - Mermaid diagram available")

    if quote_results:
        summary_lines.append("\n## Quote Verification")
        if quote_results.get("results"):
            for result in quote_results["results"]:
                label = result.get("citation", "Unknown citation")
                status = "found" if result.get("found") else "not found"
                summary_lines.append(
                    f"- Quote in {label}: {status} (similarity {result.get('similarity', 0)})"
                )
        elif quote_results.get("error"):
            summary_lines.append(f"- Error verifying quotes: {quote_results['error']}")

    summary = "\n".join(summary_lines)

    log_event(
        logger,
        "Research pipeline completed",
        tool_name="run_research_pipeline",
        request_id=request_id,
        query_params={"citation_count": len(citations)},
    )

    return {
        "summary_markdown": summary,
        "cases": case_results,
        "quotes": quote_results,
        "key_questions": questions,
        "scope": scope,
    }


@research_server.tool()
@tool_logging("run_research_pipeline")
async def run_research_pipeline(
    citations: list[str],
    key_questions: list[str] | None = None,
    scope: str | None = None,
    quotes: list[dict[str, str]] | None = None,
    request_id: str | None = None,
) -> dict[str, Any]:
    """Execute a coordinated research workflow across citations and questions.

    This tool orchestrates citation lookup, treatment classification, quote verification,
    citation network building, and mermaid rendering to produce a structured report.

    Args:
        citations: List of citations to analyze.
        key_questions: Optional research questions to guide the summary.
        scope: Optional scope or jurisdiction focus to annotate results.
        quotes: Optional list of quotes to verify.

    Returns:
        Dictionary containing a markdown summary and machine-readable sections.
    """
    return await run_research_pipeline_impl(citations, key_questions, scope, quotes, request_id)


async def issue_map_impl(
    citations: list[str],
    key_questions: list[str] | None = None,
    scope: str | None = None,
    request_id: str | None = None,
) -> dict[str, Any]:
    """Create an issue map linking key questions to cited authorities.

    Args:
        citations: Citations to analyze for issue coverage.
        key_questions: Research questions to organize findings.
        scope: Optional scope or jurisdiction focus.

    Returns:
        Dictionary with a markdown summary and structured issue map entries.
    """

    if not citations:
        return {"error": "At least one citation is required"}

    questions = _format_key_questions(key_questions or [])
    mermaid_generator = MermaidGenerator()

    case_results = []
    for citation in citations:
        case_results.append(
            await _analyze_citation(citation, scope, mermaid_generator, request_id)
        )

    issue_entries = []
    for question in questions or ["General application"]:
        entry_cases = []
        for case in case_results:
            entry_cases.append(
                {
                    "citation": case.get("citation"),
                    "case_name": case.get("case_name"),
                    "summary": case.get("summary"),
                    "treatment": case.get("treatment"),
                    "network_statistics": case.get("network", {}).get("statistics"),
                }
            )

        issue_entries.append(
            {
                "question": question,
                "related_cases": entry_cases,
                "scope": scope,
            }
        )

    summary_lines = ["# Issue Map", "## Questions"]
    for entry in issue_entries:
        summary_lines.append(f"- {entry['question']}")

    summary_lines.append("\n## Related Authorities")
    for case in case_results:
        if case.get("error"):
            summary_lines.append(f"- **{case['citation']}**: {case['error']}")
            continue
        summary = case.get("summary") or "No treatment summary available"
        summary_lines.append(
            f"- **{case.get('citation')} – {case.get('case_name', 'Unknown case')}**: {summary}"
        )

    log_event(
        logger,
        "Issue map generated",
        tool_name="issue_map",
        request_id=request_id,
        query_params={"citation_count": len(citations), "question_count": len(issue_entries)},
    )

    return {
        "summary_markdown": "\n".join(summary_lines),
        "issues": issue_entries,
        "cases": case_results,
        "key_questions": questions,
        "scope": scope,
    }


@research_server.tool()
@tool_logging("issue_map")
async def issue_map(
    citations: list[str],
    key_questions: list[str] | None = None,
    scope: str | None = None,
    request_id: str | None = None,
) -> dict[str, Any]:
    """Create an issue map linking key questions to cited authorities.

    Args:
        citations: Citations to analyze for issue coverage.
        key_questions: Research questions to organize findings.
        scope: Optional scope or jurisdiction focus.

    Returns:
        Dictionary with a markdown summary and structured issue map entries.
    """
    return await issue_map_impl(citations, key_questions, scope, request_id)


@research_server.tool()
@tool_logging("check_api_status")
async def check_api_status(request_id: str | None = None) -> dict[str, Any]:
    """Check the health and connectivity of the CourtListener API.

    Returns:
        Dictionary with status, latency, and endpoint details.
    """
    client = get_client()
    import time

    start_time = time.time()
    try:
        # We'll try a lightweight lookup, e.g. a known case or just the root endpoint if supported
        # For now, let's try to lookup Roe v. Wade as a health check
        result = await client.lookup_citation("410 U.S. 113", request_id=request_id)
        latency = time.time() - start_time

        if "error" in result:
            return {
                "status": "error",
                "error": result["error"],
                "latency_seconds": latency,
            }

        return {
            "status": "healthy",
            "latency_seconds": latency,
            "service": "CourtListener API",
            "test_citation": "410 U.S. 113"
        }
    except Exception as e:
        return {
            "status": "down",
            "error": str(e),
            "latency_seconds": time.time() - start_time
        }


async def outline_support_pipeline_impl(
    topic: str,
    primary_case: str,
    related_limit: int = 5,
    request_id: str | None = None,
) -> dict[str, Any]:
    """Generate a research outline combining semantic search and network context.

    Args:
        topic: Research topic or question to explore.
        primary_case: Anchor citation for the outline.
        related_limit: Maximum number of related authorities to include.

    Returns:
        Dictionary containing the markdown outline and structured sections.
    """

    settings = get_settings()
    query_params = {
        "topic": topic,
        "primary_case": primary_case,
        "related_limit": related_limit,
    }

    with log_operation(
        logger,
        tool_name="outline_support_pipeline",
        request_id=request_id,
        query_params=query_params,
        event="outline_support_pipeline",
    ):
        search_results, network = await asyncio.gather(
            semantic_search_impl(query=topic, limit=related_limit),
            build_citation_network_impl(
                citation=primary_case,
                max_depth=settings.network_max_depth,
                max_nodes=settings.max_citing_cases,
                include_treatments=True,
                request_id=request_id,
            ),
        )

        related_cases = [
            {
                "citation": result.get("citation"),
                "case_name": result.get("case_name"),
                "similarity_score": result.get("similarity_score"),
                "court": result.get("court"),
                "date_filed": result.get("date_filed"),
            }
            for result in search_results.get("results", [])[:related_limit]
        ]

        network_nodes = network.get("nodes") or []
        related_network_nodes = [
            node for node in network_nodes if node.get("citation") != primary_case
        ]
        network_stats = network.get("statistics") or {}

        outline_lines = [f"# Outline Support: {topic}"]
        outline_lines.append("## Doctrines & Issues")
        outline_lines.append(f"- Topic: {topic}")
        outline_lines.append(
            f"- Primary case: {primary_case} – {network.get('root_case_name', 'Unknown case')}"
        )

        outline_lines.append("\n## Related Authorities")
        if related_cases:
            for case in related_cases:
                label = case.get("citation") or "Unknown citation"
                outline_lines.append(
                    f"- **{label}** ({case.get('case_name', 'Unknown case')}): "
                    f"similarity {case.get('similarity_score', 0):.2f}"
                )
        else:
            outline_lines.append("- No related authorities found")

        outline_lines.append("\n## Citation Network Highlights")
        if network.get("error"):
            outline_lines.append(f"- Network error: {network['error']}")
        else:
            outline_lines.append(
                f"- Scope: depth {settings.network_max_depth}, nodes capped at {settings.max_citing_cases}"
            )
            outline_lines.append(
                f"- Graph: {network_stats.get('total_nodes', 0)} nodes, {network_stats.get('total_edges', 0)} edges"
            )
            if related_network_nodes:
                outline_lines.append("- Notable citing cases:")
                for node in related_network_nodes[: min(5, len(related_network_nodes))]:
                    outline_lines.append(
                        f"  - {node.get('citation', 'Unknown citation')} – {node.get('case_name', 'Unknown case')}"
                    )
            if network.get("warnings"):
                outline_lines.append("- Warnings: " + "; ".join(network["warnings"]))

        outline_lines.append(LEGAL_DISCLAIMER)
        outline_markdown = "\n".join(outline_lines)

        outline_payload = {
            "outline_markdown": outline_markdown,
            "topic": topic,
            "primary_case": primary_case,
            "primary_case_name": network.get("root_case_name"),
            "related_cases": related_cases,
            "citation_network": network,
            "doctrines": [topic],
            "network_statistics": network_stats,
        }

        log_event(
            logger,
            "Generated outline support package",
            tool_name="outline_support_pipeline",
            request_id=request_id,
            query_params=query_params,
            extra_context={
                "related_count": len(related_cases),
                "network_nodes": network_stats.get("total_nodes", 0),
            },
        )

        return outline_payload


@research_server.tool()
@tool_logging("outline_support_pipeline")
async def outline_support_pipeline(
    topic: str,
    primary_case: str,
    related_limit: int = 5,
    request_id: str | None = None,
) -> dict[str, Any]:
    """Generate a research outline combining semantic search and network context."""

    return await outline_support_pipeline_impl(
        topic=topic,
        primary_case=primary_case,
        related_limit=related_limit,
        request_id=request_id,
    )
