"""Research orchestration tools combining multiple MCP capabilities."""

from __future__ import annotations

import asyncio
import logging
from collections import defaultdict
from typing import Any, cast

from fastmcp import FastMCP

from app.analysis.deep_shepard import DeepShepardAnalyzer
from app.analysis.issue_discovery import IssueDiscoverer
from app.analysis.mermaid_generator import MermaidGenerator
from app.config import get_settings
from app.logging_config import tool_logging
from app.logging_utils import log_event, log_operation
from app.mcp_client import get_client
from app.mcp_types import ToolPayload
from app.tools.network import build_citation_network_impl
from app.tools.search import semantic_search_impl
from app.tools.treatment import check_case_validity_impl
from app.tools.verification import batch_verify_quotes_impl

LEGAL_DISCLAIMER = (
    "\n\n---\n"
    "**DISCLAIMER:** This research was generated by an AI assistant for educational and research purposes only. "
    "It does NOT constitute legal advice. All citations and treatment analysis should be independently verified "
    "before use in any legal proceeding."
)

logger = logging.getLogger(__name__)

research_server: FastMCP[ToolPayload] = FastMCP(
    name="Research Workflow Tools",
    instructions=(
        "Coordinated research tools that assemble citation lookups, treatment analysis, "
        "quote verification, citation-network building, and mermaid rendering for visual summaries."
    ),
)


async def _format_brief_summary(
    pipeline_result: dict[str, Any],
) -> str:
    """Build a concise markdown summary focused on validity and quotes."""

    summary_lines = ["# Brief Check Results"]

    summary_lines.append("\n## Case Validity")
    cases = pipeline_result.get("cases") or []
    for case in cases:
        citation_label = case.get("citation", "Unknown citation")
        case_name = case.get("case_name", "Unknown case")

        if case.get("error"):
            summary_lines.append(f"- **{citation_label}**: {case['error']}")
            continue

        treatment = case.get("treatment") if isinstance(case, dict) else None
        treatment_summary = "No treatment details available"
        if isinstance(treatment, dict):
            overall = treatment.get("overall_treatment") or treatment.get("summary")
            confidence = treatment.get("confidence")
            recommendation = treatment.get("recommendation")

            detail_parts = []
            if overall:
                detail_parts.append(str(overall))
            if confidence is not None:
                detail_parts.append(f"confidence {confidence:.2f}")
            if recommendation:
                detail_parts.append(recommendation)

            if detail_parts:
                treatment_summary = "; ".join(detail_parts)

        summary_lines.append(f"- **{citation_label} – {case_name}**: {treatment_summary}")

        if case.get("mermaid"):
            summary_lines.append("  - Mermaid visualization already available")

    quote_results = pipeline_result.get("quotes")
    if quote_results:
        summary_lines.append("\n## Quote Verification")
        results = quote_results.get("results") or []
        if results:
            for result in results:
                label = result.get("citation", "Unknown citation")
                status = "verified" if result.get("found") else "not verified"
                similarity = result.get("similarity")
                similarity_text = (
                    f" (similarity {similarity:.2f})" if similarity is not None else ""
                )
                summary_lines.append(f"- {label}: {status}{similarity_text}")
        elif quote_results.get("error"):
            summary_lines.append(f"- Error verifying quotes: {quote_results['error']}")

    return "\n".join(summary_lines)


def _format_key_questions(key_questions: list[str]) -> list[str]:
    """Normalize the key questions list."""
    return [q for q in key_questions if q.strip()]


async def _analyze_citation(
    citation: str,
    scope: str | None,
    mermaid_generator: MermaidGenerator,
    request_id: str | None,
    job_id: str | None,
) -> dict[str, Any]:
    """Gather treatment, network, and visualization details for a citation."""
    query_params = {"citation": citation, "scope": scope}
    settings = get_settings()
    client = get_client()

    with log_operation(
        logger,
        tool_name="research_pipeline_case",
        request_id=request_id,
        job_id=job_id,
        query_params=query_params,
        event="research_pipeline_case",
    ):
        lookup = await client.lookup_citation(citation, request_id=request_id)

        if "error" in lookup:
            return {"citation": citation, "error": lookup.get("error", "Lookup failed")}

        treatment = await check_case_validity_impl(citation, request_id=request_id, job_id=job_id)
        network = await build_citation_network_impl(
            citation=citation,
            max_depth=settings.network_max_depth,
            max_nodes=settings.max_citing_cases,
            include_treatments=True,
            request_id=request_id,
            job_id=job_id,
        )

        mermaid = None
        deep_shepard_results = None
        if "error" not in network and network.get("nodes"):
            mermaid = mermaid_generator.generate_flowchart(network)

            # Run deep shepardizing analysis
            from app.analysis.deep_shepard import DeepShepardAnalyzer, reconstruct_citation_network

            citation_network_obj = reconstruct_citation_network(network)
            if citation_network_obj:
                analyzer = DeepShepardAnalyzer()
                deep_shepard_results = analyzer.analyze(
                    citation_network_obj, request_id=request_id, job_id=job_id
                )

        case_summary = treatment.get("summary") if isinstance(treatment, dict) else None

        # Add deep shepard warnings to summary if there are high-risk cases
        if deep_shepard_results:
            high_risk_cases = [
                status
                for status in deep_shepard_results.values()
                if status.get("risk_score", 0.0) >= 0.7
            ]
            if high_risk_cases:
                deep_shepard_warnings = [
                    f"⚠️ Deep Shepardizing Warning: {status['citation']} ({status.get('case_name', 'Unknown')}) "
                    f"has risk score {status['risk_score']:.2f} - {status.get('recommendation', '')}"
                    for status in high_risk_cases
                ]
                if case_summary:
                    case_summary += "\n\n" + "\n".join(deep_shepard_warnings)
                else:
                    case_summary = "\n".join(deep_shepard_warnings)

        log_event(
            logger,
            "Completed research aggregation for citation",
            tool_name="research_pipeline_case",
            request_id=request_id,
            query_params=query_params,
            extra_context={
                "case_name": lookup.get("caseName"),
                "has_mermaid": bool(mermaid),
                "deep_shepard_suspects": len(deep_shepard_results) if deep_shepard_results else 0,
            },
        )

        return {
            "citation": citation,
            "case_name": lookup.get("caseName"),
            "court": lookup.get("court"),
            "date_filed": lookup.get("dateFiled"),
            "treatment": treatment,
            "network": network,
            "mermaid": mermaid,
            "summary": case_summary,
            "deep_shepard_analysis": deep_shepard_results,
        }


async def run_research_pipeline_impl(
    citations: list[str],
    key_questions: list[str] | None = None,
    scope: str | None = None,
    quotes: list[dict[str, str]] | None = None,
    request_id: str | None = None,
    job_id: str | None = None,
) -> dict[str, Any]:
    """Execute a coordinated research workflow across citations and questions."""
    if not citations:
        return {"error": "At least one citation is required"}

    questions = _format_key_questions(key_questions or [])
    mermaid_generator = MermaidGenerator()

    case_results = []
    for citation in citations:
        case_results.append(
            await _analyze_citation(citation, scope, mermaid_generator, request_id, job_id)
        )

    quote_results: dict[str, Any] | None = None
    if quotes:
        quote_results = await batch_verify_quotes_impl(quotes, request_id=request_id, job_id=job_id)

    summary_lines: list[str] = ["# Research Pipeline Summary"]
    if scope:
        summary_lines.append(f"*Scope:* {scope}")

    summary_lines.append("## Key Questions")
    if questions:
        summary_lines.extend([f"- {question}" for question in questions])
    else:
        summary_lines.append("- No key questions provided")

    summary_lines.append("\n## Case Findings")
    for case in case_results:
        if case.get("error"):
            summary_lines.append(f"- **{case['citation']}**: {case['error']}")
            continue

        summary = case.get("summary") or "No treatment summary available"
        citation_label = f"{case.get('citation')} – {case.get('case_name', 'Unknown case')}"
        summary_lines.append(f"- **{citation_label}**: {summary}")

        network_stats = case.get("network", {}).get("statistics")
        if network_stats:
            summary_lines.append(
                f"  - Network: {network_stats.get('total_nodes', 0)} nodes, "
                f"{network_stats.get('total_edges', 0)} edges"
            )
        if case.get("mermaid"):
            summary_lines.append("  - Mermaid diagram available")

    if quote_results:
        summary_lines.append("\n## Quote Verification")
        if quote_results.get("results"):
            for result in quote_results["results"]:
                label = result.get("citation", "Unknown citation")
                status = "found" if result.get("found") else "not found"
                summary_lines.append(
                    f"- Quote in {label}: {status} (similarity {result.get('similarity', 0)})"
                )
        elif quote_results.get("error"):
            summary_lines.append(f"- Error verifying quotes: {quote_results['error']}")

    summary = "\n".join(summary_lines)

    log_event(
        logger,
        "Research pipeline completed",
        tool_name="run_research_pipeline",
        request_id=request_id,
        job_id=job_id,
        query_params={"citation_count": len(citations)},
    )

    return {
        "summary_markdown": summary,
        "cases": case_results,
        "quotes": quote_results,
        "key_questions": questions,
        "scope": scope,
        "job_id": job_id,
    }


@research_server.tool()
@tool_logging("run_research_pipeline")
async def run_research_pipeline(
    citations: list[str],
    key_questions: list[str] | None = None,
    scope: str | None = None,
    quotes: list[dict[str, str]] | None = None,
    request_id: str | None = None,
    job_id: str | None = None,
) -> dict[str, Any]:
    """Execute a coordinated research workflow across citations and questions."""
    return await run_research_pipeline_impl(
        citations, key_questions, scope, quotes, request_id, job_id
    )


@research_server.tool()
@tool_logging("brief_check_pipeline")
async def brief_check_pipeline(
    citations: list[str],
    quotes: list[dict[str, str]] | None = None,
    request_id: str | None = None,
    job_id: str | None = None,
) -> dict[str, Any]:
    """Run a concise validity + quote check preset for multiple citations."""
    pipeline_result = await run_research_pipeline_impl(
        citations=citations,
        key_questions=None,
        scope=None,
        quotes=quotes,
        request_id=request_id,
        job_id=job_id,
    )

    if "error" in pipeline_result:
        return pipeline_result

    summary = await _format_brief_summary(pipeline_result)

    return {
        **pipeline_result,
        "summary_markdown": summary,
    }


async def issue_map_impl(
    citations: list[str] | None = None,
    primary_case: str | None = None,
    key_questions: list[str] | None = None,
    scope: str | None = None,
    request_id: str | None = None,
) -> dict[str, Any]:
    """Create an issue map linking key questions to cited authorities.

    Now supports auto-discovery of issues if citations/text don't match provided questions.
    """
    if not citations and not primary_case:
        return {"error": "At least one citation or a primary case is required"}

    client = get_client()
    discoverer = IssueDiscoverer()
    questions = _format_key_questions(key_questions or [])

    # Collect cases to process with their text context
    cases_to_process = []

    if primary_case:
        citing_result = await client.find_citing_cases(
            primary_case, limit=50, request_id=request_id
        )
        raw_results = citing_result.get("results")
        if isinstance(raw_results, list):
            for c in raw_results:
                if not isinstance(c, dict):
                    continue
                cases_to_process.append(
                    {
                        "citation": c.get("citation", ["?"])[0],
                        "case_name": c.get("caseName"),
                        "text_context": c.get("snippet") or "",
                        "source": "citing_primary",
                    }
                )

    if citations:
        for cite in citations:
            if any(x["citation"] == cite for x in cases_to_process):
                continue

            c = await client.lookup_citation(cite, request_id=request_id)
            if "error" in c:
                continue

            # For lookup results, we might not have a "citing snippet" because it's the case itself.
            # But we can try to find what it talks about from syllabus.
            cases_to_process.append(
                {
                    "citation": cite,
                    "case_name": c.get("caseName"),
                    "text_context": c.get("syllabus") or c.get("snippet") or "",
                    "source": "user_list",
                }
            )

    # Grouping Logic
    issues: defaultdict[str, dict[str, Any]] = defaultdict(
        lambda: {"source": "auto_discovered", "supporting_cases": []}
    )

    # Initialize user questions
    for q in questions:
        issues[q] = {"source": "user", "supporting_cases": []}

    for case in cases_to_process:
        text = case["text_context"]
        citation = case["citation"]
        matched = False

        # 1. Try matching user questions
        for q in questions:
            # Simple keyword matching: checks if significant words from question appear in text
            # This is "coarse" but fits the requirement.
            keywords = [w.lower() for w in q.split() if len(w) > 4]
            if keywords and any(k in text.lower() for k in keywords):
                issues[q]["supporting_cases"].append(
                    {
                        "citation": citation,
                        "case_name": case["case_name"],
                        "snippet": text[:200] + "...",
                    }
                )
                matched = True
                break

        if matched:
            continue

        # 2. Auto-discovery
        discovery = discoverer.discover_issue(text, citation)
        label = discovery["label"]
        source = discovery["source"]

        # If label is generic, maybe group under "Other"
        if label == "General Application" and not questions:
            # Keep it
            pass
        elif label == "General Application":
            label = "Unclassified"

        if label not in issues:
            issues[label] = {"source": "auto_discovered", "supporting_cases": []}

        issues[label]["supporting_cases"].append(
            {
                "citation": citation,
                "case_name": case["case_name"],
                "snippet": text[:200] + "...",
                "discovery_method": source,
            }
        )

    # Format output
    final_issues = []
    for label, data in issues.items():
        if data["supporting_cases"]:
            final_issues.append(
                {
                    "label": label,
                    "source": data["source"],
                    "supporting_cases": data["supporting_cases"],
                }
            )

    summary_lines = ["# Issue Map"]
    if primary_case:
        summary_lines.append(f"Primary Case: {primary_case}")

    for issue in final_issues:
        summary_lines.append(f"\n## {issue['label']} ({issue['source']})")
        for case in issue["supporting_cases"][:5]:  # Limit for summary
            summary_lines.append(f"- **{case['citation']}**: {case['case_name']}")

    return {
        "summary_markdown": "\n".join(summary_lines),
        "issues": final_issues,
        "primary_case": primary_case,
        "scope": scope,
    }


@research_server.tool()
@tool_logging("issue_map")
async def issue_map(
    citations: list[str] | None = None,
    primary_case: str | None = None,
    key_questions: list[str] | None = None,
    scope: str | None = None,
    request_id: str | None = None,
) -> dict[str, Any]:
    """Create an issue map linking key questions to cited authorities.

    Can cluster citations by issue using user-provided questions or auto-discovery
    from section headings.

    Args:
        citations: Optional list of citations to analyze.
        primary_case: Optional primary case to find citing cases for.
        key_questions: Research questions to organize findings.
        scope: Optional scope.
    """
    return await issue_map_impl(citations, primary_case, key_questions, scope, request_id)


@research_server.tool()
@tool_logging("check_api_status")
async def check_api_status(request_id: str | None = None) -> dict[str, Any]:
    """Check the health and connectivity of the CourtListener API."""
    client = get_client()
    import time

    start_time = time.time()
    try:
        result = await client.lookup_citation("410 U.S. 113", request_id=request_id)
        latency = time.time() - start_time

        if isinstance(result, dict) and "error" in result:
            error_info = cast(dict[str, Any], result)
            return {
                "status": "error",
                "error": error_info["error"],
                "latency_seconds": latency,
            }

        return {
            "status": "healthy",
            "latency_seconds": latency,
            "service": "CourtListener API",
            "test_citation": "410 U.S. 113",
        }
    except Exception as e:
        return {"status": "down", "error": str(e), "latency_seconds": time.time() - start_time}


async def outline_support_pipeline_impl(
    topic: str,
    primary_case: str,
    related_limit: int = 5,
    request_id: str | None = None,
) -> dict[str, Any]:
    """Generate a research outline combining semantic search and network context."""

    settings = get_settings()
    query_params = {
        "topic": topic,
        "primary_case": primary_case,
        "related_limit": related_limit,
    }

    with log_operation(
        logger,
        tool_name="outline_support_pipeline",
        request_id=request_id,
        query_params=query_params,
        event="outline_support_pipeline",
    ):
        search_results, network = await asyncio.gather(
            semantic_search_impl(query=topic, limit=related_limit),
            build_citation_network_impl(
                citation=primary_case,
                max_depth=settings.network_max_depth,
                max_nodes=settings.max_citing_cases,
                include_treatments=True,
                request_id=request_id,
            ),
        )

        related_cases = [
            {
                "citation": result.get("citation"),
                "case_name": result.get("case_name"),
                "similarity_score": result.get("similarity_score"),
                "court": result.get("court"),
                "date_filed": result.get("date_filed"),
            }
            for result in search_results.get("results", [])[:related_limit]
        ]

        network_nodes = network.get("nodes") or []
        related_network_nodes = [
            node for node in network_nodes if node.get("citation") != primary_case
        ]
        network_stats = network.get("statistics") or {}

        outline_lines = [f"# Outline Support: {topic}"]
        outline_lines.append("## Doctrines & Issues")
        outline_lines.append(f"- Topic: {topic}")
        outline_lines.append(
            f"- Primary case: {primary_case} – {network.get('root_case_name', 'Unknown case')}"
        )

        outline_lines.append("\n## Related Authorities")
        if related_cases:
            for case in related_cases:
                label = case.get("citation") or "Unknown citation"
                outline_lines.append(
                    f"- **{label}** ({case.get('case_name', 'Unknown case')}): "
                    f"similarity {case.get('similarity_score', 0):.2f}"
                )
        else:
            outline_lines.append("- No related authorities found")

        outline_lines.append("\n## Citation Network Highlights")
        if network.get("error"):
            outline_lines.append(f"- Network error: {network['error']}")
        else:
            outline_lines.append(
                f"- Scope: depth {settings.network_max_depth}, nodes capped at {settings.max_citing_cases}"
            )
            outline_lines.append(
                f"- Graph: {network_stats.get('total_nodes', 0)} nodes, {network_stats.get('total_edges', 0)} edges"
            )
            if related_network_nodes:
                outline_lines.append("- Notable citing cases:")
                for node in related_network_nodes[: min(5, len(related_network_nodes))]:
                    outline_lines.append(
                        f"  - {node.get('citation', 'Unknown citation')} – {node.get('case_name', 'Unknown case')}"
                    )
            if network.get("warnings"):
                outline_lines.append("- Warnings: " + "; ".join(network["warnings"]))

        outline_lines.append(LEGAL_DISCLAIMER)
        outline_markdown = "\n".join(outline_lines)

        outline_payload = {
            "outline_markdown": outline_markdown,
            "topic": topic,
            "primary_case": primary_case,
            "primary_case_name": network.get("root_case_name"),
            "related_cases": related_cases,
            "citation_network": network,
            "doctrines": [topic],
            "network_statistics": network_stats,
        }

        log_event(
            logger,
            "Generated outline support package",
            tool_name="outline_support_pipeline",
            request_id=request_id,
            query_params=query_params,
            extra_context={
                "related_count": len(related_cases),
                "network_nodes": network_stats.get("total_nodes", 0),
            },
        )

        return outline_payload


@research_server.tool()
@tool_logging("outline_support_pipeline")
async def outline_support_pipeline(
    topic: str,
    primary_case: str,
    related_limit: int = 5,
    request_id: str | None = None,
) -> dict[str, Any]:
    """Generate a research outline combining semantic search and network context."""

    return await outline_support_pipeline_impl(
        topic=topic,
        primary_case=primary_case,
        related_limit=related_limit,
        request_id=request_id,
    )
